### ISSUE TITLE
24 May 2022 UI monthly meeting

### ISSUE THREAD

**Issue by valeriavitale** [machines-reading-maps/Rumsey-MRM#12]

**Comment by valeriavitale** [comment]
Agenda for the User Interface May meeting

- [ ] Some initial design ideas from @rsimon 
- [ ] Some feedback on the proposals + discussion around some visualisation issues
- [ ] Dynamics and rules of annotation and validation: logged users vs anonymous, traffic-light system (or other visual clues), access to annotations from different user journeys.
- [ ] How to display and encourage "stories".

**Comment by kmcdono2** [comment]
let's add agenda items for 
- David Wong to report on and discuss  solr-related isssues (e.g. indexing/string-matching)
- @valeriavitale on how user profiles are informing the decisions above (or at what stage these profiles become important)
