### ISSUE TITLE
26 July 2022 UI meeting

### ISSUE THREAD

**Issue by valeriavitale** [machines-reading-maps/Rumsey-MRM#15]

**Comment by valeriavitale** [comment]
- [ ] Recogito-Luna integration

**Comment by dwong2006** [comment]
> Filter annotations by score? What score is considered good enough?

**Comment by kmcdono2** [comment]
Notes about data curation re: types of annotations we will be ultimately storing:
a. mapKurator output
b. user annotation (first edit)
c. user annotation (second edit)

User annotations could be completely new (e.g. drawing a bounding polygon, transcribing, etc.) OR they could be editing a mapKurator output that is entirely or partially incorrect.

**Comment by valeriavitale** [comment]
Notes:
RS: we should discuss more the workflow between Recogito and Luna.
DW: the user interface will be part of Luna or sit outiside of it?
RS: it's to be discussed. It could be outside of Luna, especially if people are only browsing annotations. But also good to have a separate static front end for editing the annotations. There could be a sort of "holding space" for not confirmed annotations, before being sent to Luna.
DZ: Can we add a time stamp to annotations? It could help with the indexing. (See IIIF change API). WE could schedule the updates of the annotations.
RS: yes, we can add timestamps on annotations.
DZ: so we can only update what is necessary.
DW: annotations need a unique identifier. 
RS: we have IDs for the mapKurator annotations, and edits will keep the same. But we need to have random IDs for the "stories".
DZ: If you edit an annotation in Luna, and it is fully legit, it should go back to the main server.
KmD: what is the kind of data we are currently aiming for? At this point we are mostly imagining people correcting mapKurator output.
DZ: where the different status of annotations live? Do they live in the same server?
RS: Luna should be controlling the original annotations. If a user does edits, it should go in the temporary server. Here we can record if an annotation have been checked twice and make those permanent and send them back to my SQLdatabase.
VV: we can have three status: machine generated, checked once, checked twice (agreement)

**Comment by valeriavitale** [comment]
DW: we could also pull from multiple annotation sources.
RS: could we share the log in feature with Luna? Currently we just have a static front end.
DZ: we support several authentication systems, including Shibboleth.
RS: JSON web token could be a good approach, we act as a client and just recognise that the user is already logged into Luna.
DZ: we should look into what IIIF is doing. They are very good, plus we want to develop things with IIIF in mind.
To do for everyone: look into authentication approaches, especially IIIF

**Comment by valeriavitale** [comment]
DW: we can have multiple sources to pull from, but one single submission server
RS: annotations are de-referenceable, and there is already an API with path+URI. User draws a box, it gets stored on the annotation server. It will show as a new annotation and be fetched as an update.
DW: Annotation search is already supported in IIIF, but we can expand that

**Comment by valeriavitale** [comment]
DZ: what are the next steps?
RS: the webGL implementation (as shown in the demo), and the authentication.
DZ: where things will be hosted?
KmD: we could try USC (that will be hosting MRM), or Stanford Library
DZ: we had some issues with throttling with them in the past.
RS: we have two things to host: the mapKurator for the processing and the annotations database (which would be a light load)
DZ: we can start putting it on one of our dev servers, for the short term. What about Archive.org
KmD: They just hired [Thomas Padilla](https://www.thomaspadilla.org/), who knows MRM and seems the right person to talk to.

**Comment by valeriavitale** [comment]
DW: what does the confidence score mark? what is a good confidence score? are we displaying all of them?
KmD: this is a very useful piece of information, and could be used to filter the annotations. We should look at the new processed maps with this in mind.
DZ: we could have a default view, but give people the opportunity to filter.
KmD: we also need to think about how this interact with fuzzy string matching.
