### ISSUE TITLE
6 Sept 2022 UI meeting

### ISSUE THREAD

**Issue by kmcdono2** [machines-reading-maps/Rumsey-MRM#16]
Agenda

- Q: Does Luna have the data from UMN?
- Update from Luna
- Update from @rsimon 
- @valeriavitale to discuss concerns around linking to gazetteers from a user perspective (which ones, why/why not, how, when/who)
- When will be we ready to test search/annotation, and what do we want to know? (set up co-working meetings for this)

**Comment by kmcdono2** [comment]
FYI - previous discussion about annotation features/issues #10

**Comment by rsimon** [comment]
Architecture questions/proposal:
https://docs.google.com/presentation/d/1QUEVkl5lFGie_CyULkGmnIYJkEYNpwrLYwYkc59yVNw/edit?usp=drivesdk

**Comment by kmcdono2** [comment]
Q for next time: what categories will we allow for search?
<img width="1285" alt="Screen Shot 2022-09-06 at 09 38 23" src="https://user-images.githubusercontent.com/20363927/188695421-b362e404-1b75-4082-aa5d-9820a990b4c8.png">

**Comment by kmcdono2** [comment]
For documenting the mapKurator data: https://huggingface.co/docs/hub/datasets-cards
