### ISSUE TITLE
29 March 2022 Monthly Meeting

### ISSUE THREAD

**Issue by valeriavitale** [machines-reading-maps/Rumsey-MRM#2]

**Comment by valeriavitale** [comment]
- [ ] General Business
> Standing agenda format (and allocated time for item)
> Quick internal communication channel
- [ ] Research and Development Updates
> Presenting 6 months goals
> Comparison with ABCnet performance

**Comment by kmcdono2** [comment]
ACTION ITEMS

- add Drake and Michelle to slack and Github repo

NOTES
- for checking # of georeferenced maps see https://www.davidrumsey.com/view/georeferencer

**Comment by valeriavitale** [comment]
Standing agenda template has been approved. Agenda will be circulated a week in advance for everyone to contribute. Agendas will be hosted as public tickets on our GitHub repository, and remain accessible at any time. Notes for the meeting (including links to external resources) can be archived as comments below the agenda. Items for the agenda can also be emailed to Valeria, if that is a preferable option.

We will use a combination of platforms for communication, mainly the GitHub project board and a dedicated Slack Channel. Emails, of course, will still be used for in depth communication.

**Comment by valeriavitale** [comment]
In the Old Maps Online metadata, the value in the field "external_id" is the one MRM should be look for, in order to match the file names in Luna. Drake will send Zekun some sample queries. The information about a map being geo-referenced or not is currently not recorded in the Luna metadata. To check if a map has been georeferenced, we need to search if it is in the list in the georeferencer.

Complete metadata export from Luna may be complicated, as the collection includes a number of documents who are not strictly maps, and need to be filtered out.

**Comment by valeriavitale** [comment]
Numbers on such a variety of maps can be an overwhelming task. At this stage, MRM will only focus in place names. Numbers will be detected, but not transcribed nor linked to any external KB.

One of the outcomes of the project could be the automatic identification of language, and the generation of value for a "language" field in the metadata, making the collection searchable under a different perspective.

The area outside the neatline is confirmed as a topic of interest in this project, being the main source for information that fills the metadata.

**Comment by valeriavitale** [comment]
Annotations guidelines are being developed. They will take into account the ML performance, the creation of research data, the future contribution of the public.

Ideally, there will be two ways of searching and exploring the collection: one through the metadata and one through the annotation. This should fit well with the existing structure in Luna, that is already able to store them separately.

**Comment by valeriavitale** [comment]
Comparison with the performance of ABCnet has showed areas where mapKurator could be improved, incorporating some of the functions of ABCnet, where the latter returns better results. Detection of non-Latin alphabet is currently very low for both mapKurator and ABCnet, because they have only been trained on Latin characters. But mapKurator aims to experiment with non-Latin alphabets in the near future and improve the performance.

**Comment by valeriavitale** [comment]
Next meeting is scheduled for Tuesday 3 May 2022 at 09:00 PDT/11:00 CDT/17:00 BST/18:00 CEST
