### ISSUE TITLE
pick initial sample of maps

### ISSUE THREAD

**Issue by kmcdono2** [machines-reading-maps/Rumsey-MRM#7]
Request from @yaoyichi to pick initial sample of 100 maps from DR collection for testing.

Questions to guide selection (@yaoyichi @zekun-li @Jina-Kim could you answer these to help us make appropriate decisions?)
- [x] will we be fully annotating these maps (e.g. everything from bounding polygons to gazetteer links and semantic type tags)? (If so, we will only select maps from where we have gazetteer coverage. So we should be strategic)
- [x] Confirming that this initial sample should all be latin script (e.g. "ABCD", not Arabic or ancient Greek)?
- [x] Should we include world- or hemisphere-scale maps? (This raises a problem with the KBs that we need to resolve. So if this is a priority we also need to plan for this task.)

**Comment by yaoyichi** [comment]
1. we can assume that we will fully annotate these maps; however, we might be able to do it.
2. yes, Latin scripts and preferably English scripts
3. I'd prefer large scale maps that cover a smaller area and could have interesting details in the scripts (not to say that small scales maps are not interesting)

**Comment by kmcdono2** [comment]
Great!! This makes selection much easier. I will sneak a couple of French maps in if that's OK...

**Comment by kmcdono2** [comment]
We are listing the maps [here](https://docs.google.com/spreadsheets/d/1RcwsC6LHOyb9-27LpAaYWdFLJDQdx__fpPdbYAK3aiY/edit#gid=0)

**Comment by kmcdono2** [comment]
@yaoyichi there is a start to the list of maps, if you want to get working on those :) We will keep working on the list today and Monday.

**Comment by kmcdono2** [comment]
@yaoyichi @zekun-li @Jina-Kim This list of 100 maps is now complete!
